### ISSUE TITLE
We need the Kiepert point data

### ISSUE THREAD

**Issue by gregorycrane** [pnadelofficial/keipert_atlas_georeferencing#3]
We want to combine 

* point data from Kiepert
* alignments with Pleiades
* create a map showing implicit admin districts by using a color to map points in a given region
** gets us past the problem of the imprecise boundaries of the polygons (though those are super cool!) 

![image](https://user-images.githubusercontent.com/5159577/205205204-daa56b1c-5f55-4ce0-8e8d-e61832e22c05.png)

**Comment by pnadelofficial** [comment]
We have this data as well. This is mostly what I did last summer. I'm not sure how it works with geojson, but I can put it up here either as geojson or a similar form. I'll also post the geodatabase for it so someone could use it in arcgis too.

**Comment by pnadelofficial** [comment]
I just added this. Let me know if you're having trouble using it.
